# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Create < Formula
  desc "A modern UNIX file generation tool"
  homepage "https://github.com/bschaatsbergen/create"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bschaatsbergen/create/releases/download/v0.1.0/create_0.1.0_darwin_arm64.tar.gz"
      sha256 "89fc4c0944f25064d234f186f842a5081b9d7bcdc7e0d56dfd5e09daa6afee0c"

      def install
        bin.install "create"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bschaatsbergen/create/releases/download/v0.1.0/create_0.1.0_darwin_amd64.tar.gz"
      sha256 "2858f47939556a45a47adfb40592ca91864d3443922a9cb79f9cb989a3bd7c91"

      def install
        bin.install "create"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bschaatsbergen/create/releases/download/v0.1.0/create_0.1.0_linux_arm64.tar.gz"
      sha256 "1f048e992ac9b8219aa4972e0b410819a936a3836dc41008958fc978c441c716"

      def install
        bin.install "create"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bschaatsbergen/create/releases/download/v0.1.0/create_0.1.0_linux_amd64.tar.gz"
      sha256 "ac0e23fd506df583ba59e87ae11d71f0324a781381ec275abf59e47dcdbd6920"

      def install
        bin.install "create"
      end
    end
  end

  test do
    system "#{bin}/create -v"
  end
end
